DECLARE @SQLTemplate AS VARCHAR(MAX) =
'WITH ROWCOUNTS AS (
{@SQL}
)
SELECT *
FROM ROWCOUNTS
ORDER BY NUMROWS DESC
;';
DECLARE @SQL AS VARCHAR(MAX);

SELECT @SQL = REPLACE(@SQLTemplate, '{@SQL}', STUFF((SELECT ' UNION ALL SELECT TABLENAME = ''' + TABLE_NAME + ''', NUMROWS = COUNT(*) FROM ' + QUOTENAME(TABLE_NAME) + CHAR(13) + CHAR(10)
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
FOR XML PATH(''), TYPE).value('.', 'varchar(max)'), 1, LEN(' UNION ALL '), ''));

-- PRINT @SQL;
EXEC (@SQL);